<?php
/*
///##### STOP! #####\\\
DO NOT EDIT THIS FILE DIRECTLY
This file is mamanged by GIT
Contribute at https://github.com/cchsctv/cchsctv.com/
*/
$page_title = "Not Found";
require 'header.php';
require 'topnav.php';
?>

<div style="padding:1em">
  <!--<img src="ctv_images/logo.png" data-rjs="3"
  style="width:100%; max-width:350px; margin:auto; display:block"> -->

  <p style="
  text-align:center;
  font-family: HelveticaNeue-Light, Helvetica, Arial, sans-serif;
  font-weight:lighter;
	font-size: 2.25em;
  ">The page your looking for doesn't exist</a>
</div>



<?php require 'footer.php' ?>
