<?php
/*
///##### STOP! #####\\\
DO NOT EDIT THIS FILE DIRECTLY
This file is mamanged by GIT
Contribute at https://github.com/cchsctv/cchsctv.com/
*/
$page_title ="Alumni";
require 'header.php';
?>
<style type="text/css">
p {
	font-family: HelveticaNeue-Light, Helvetica, Arial, sans-serif;
}
p.style{
	font-size: 14px;
	color:white;
	margin:0px;
	letter-spacing:1px;
}
p.alum{
  text-align: left;
	font-size: 14px;
	color:white;
	margin:0px;
}
b.name{
	padding-left: 0.25em;
	font-size: 18px;
}
p.title {
  text-align: center;
  font-size: 18px;
}
.row {
  width:100%;
	line-height: 1.75em
}
.row:nth-of-type(even) {
	background: #F0F0F0;
  background: #373737;
}
.row:nth-of-type(odd) {
	background: #FFFFFF;
  background: #303030;
}
.row .title{
	background-color: #c30e0e;
	width:100%;
}
.class_of {
  width:100%;
  height:auto;
	display: block;
}
.stripe {
  border-bottom: 10px black solid;
}
@media only screen and (max-width: 720px) {
  .topnav a:not(:nth-child(4)) {
    display: none;
  }
  .topnav a:nth-child(4) {
    display: inherit;
  }
	.class_of {
		border-bottom: 10px solid black;
	}
}
</style>

<?php
require 'topnav.php';
?>

<!-- PAGE BEGIN-->

<!-- CLASS YEAR START --><a name=""></a><!--  ***** DO NOT UNHIDE *****
<img class="edge2edge class_of" src="ctv_images/co2017.jpg" alt="Class Of 2017"><div class="stripe">
<div class="row"><p class="alum title"><b>2017 SENIOR OFFICERS:</b></div>
<div class="row"><p class="alum">
  <b class="name">Lian Chung-Valuntas</b> <i>President,</i> University of Centrial Florida</p></div>
<div class="row"><p class="alum">
  <b class="name">Jason Chua</b> <i>Operations Manager,</i> Florida Polytechnic University</p></div>
<div class="row"><p class="alum" align="center">
  <b class="name">2017 SENIOR STAFF:</b></p></div>
<div class="row"><p class="alum">
  <b class="name">Emily Ehrlich</b> Florida State University</p></div>
<div class="row"><p class="alum">
  <b class="name">Lyndsey Kleiman</b> University of Florida</p></div>
<div class="row"><p class="alum">
  <b class="name">Krzysza Korytkowski</b> Broward College</p></div>
<div class="row"><p class="alum">
  <b class="name">Jemma Miller</b> Miami Dade College</p></div>
<div class="row"><p class="alum">
  <b class="name">Sergio Owen</b> Florida International University</p></div>
<div class="row"><p class="alum">
  <b class="name">Anna Villalonga</b> Nova Southeastern University</p></div>
<div class="row"><p class="alum" align="center">
  <b class="name">OTHER DEPARTING STAFF:</b></p></div>
<div class="row"><p class="alum">
  <b class="name">Lexi Delgado</b> <i>Vice President,</i> Early Admission</p></div>
<div class="row"><p class="alum">
  <b class="name">Kiara Bencosme</b> </p></div>
<div class="row"><p class="alum">
  <b class="name">Madison Gailboord</b> </p></div>
<div class="row"><p class="alum">
  <b class="name">Danielle Siso</b> </p></div>
<div class="row"><p class="alum">
  <b class="name">Douglas Weimann</b> </p></div>
</div>-->
<!-- CLASS YEAR END -->

<!-- CLASS YEAR START --><a name="18"></a>
<img class="edge2edge class_of" src="ctv_images/co2018.jpg" alt="Class Of 2018" data-rjs="3"><div class="stripe">
<div class="row"><p class="alum title"><b>2018 SENIOR OFFICERS:</b></div>
<div class="row"><p class="alum"><b class="name">Casey Chapter</b> <i>President,</i> Florida State University </p></div>
<div class="row"><p class="alum"><b class="name">Ashton Bosse</b> <i>Vice President,</i> University of Central Florida</p></div>
<div class="row"><p class="alum"><b class="name">Jakob Wolk</b> <i>Assistant Vice President,</i> Arizona State University</p></div>
<div class="row"><p class="alum"><b class="name">Brianna Franco</b> <i>Treasurer,</i> University of Central Florida</p></div>
<div class="row"><p class="alum"><b class="name">Rebecca Smitherman</b> <i>Historian,</i> Florida State University</p></div>
<div class="row"><p class="alum"><b class="name">Jacob Mayer</b> <i>Operations Manager,</i> Florida State University</p></div>
<div class="row"><p class="alum title"><b>2018 SENIOR STAFF:</b></p></div>
<div class="row"><p class="alum"><b class="name">Chad Allen</b> Broward College</p></div>
<div class="row"><p class="alum"><b class="name">Mark Brent</b> Florida Institute of Technology</p></div>
<div class="row"><p class="alum"><b class="name">Kalya Burge</b> University of Central Florida</p></div>
<div class="row"><p class="alum"><b class="name">Adam Glantz</b> <i>Sports Director,</i> University of Central Florida</p></div>
<div class="row"><p class="alum"><b class="name">Jenna Knight</b> University of Central Florida</p></div>
<div class="row"><p class="alum"><b class="name">Jessica Less</b> University of Central Florida</p></div>
<div class="row"><p class="alum"><b class="name">Felipe Lopez</b> Boston University</p></div>
<div class="row"><p class="alum"><b class="name">Harris Ness</b> <i>Entertainment Director,</i> San Diego State University</p></div>
<div class="row"><p class="alum"><b class="name">Mario Sculac</b> University of Twente</p></div>
<div class="row"><p class="alum"><b class="name">Isabella Tocci</b> <i>News Director, </i> Florida State University</p></div>
</div>
<!-- CLASS YEAR END -->

<!-- CLASS YEAR START --><a name="17"></a>
<img class="edge2edge class_of" src="ctv_images/co2017.jpg" alt="Class Of 2017" data-rjs="3"><div class="stripe">
<div class="row"><p class="alum title"><b>2017 SENIOR OFFICERS:</b></div>
<div class="row"><p class="alum"><b class="name">Lian Chung-Valuntas</b> <i>President,</i> University of Central Florida</p></div>
<div class="row"><p class="alum"><b class="name">Jason Chua</b> <i>Operations Manager,</i> Florida Polytechnic University</p></div>
<div class="row"><p class="alum title"><b>2017 SENIOR STAFF:</b></p></div>
<div class="row"><p class="alum"><b class="name">Emily Ehrlich</b> University of Florida</p></div>
<div class="row"><p class="alum"><b class="name">Lyndsey Kleiman</b> University of Florida</p></div>
<div class="row"><p class="alum"><b class="name">Krzysza Korytkowski</b> Florida International University</p></div>
<div class="row"><p class="alum"><b class="name">Jemma Miller</b> Florida State University</p></div>
<div class="row"><p class="alum"><b class="name">Sergio Owen</b> Broward College</p></div>
<div class="row"><p class="alum"><b class="name">Kalli Rogers</b> Florida State University</p></div>
<div class="row"><p class="alum"><b class="name">Justine Russo</b> University of Central Florida</p></div>
<div class="row"><p class="alum"><b class="name">Anna Villalonga</b> <i>Sports Director,</i> Columbia College Chicago</p></div>
<div class="row"><p class="alum title"><b>OTHER DEPARTING STAFF:</b></p></div>
<div class="row"><p class="alum"><b class="name">Kiara Bencosme</b> </p></div>
<div class="row"><p class="alum"><b class="name">Lexi Delgado</b> <i>Vice President</i></p></div>
<div class="row"><p class="alum"><b class="name">Madison Gailboord</b> </p></div>
<div class="row"><p class="alum"><b class="name">Danielle Siso</b> </p></div>
<div class="row"><p class="alum"><b class="name">Douglas Weimann</b> </p></div>
</div>
<!-- CLASS YEAR END -->

<!-- CLASS YEAR START --><a name="16"></a>
<img class="edge2edge class_of" src="ctv_images/co2016.jpg" alt="Class Of 2016" data-rjs="2"><div class="stripe">
<div class="row"><p class="alum title"><b>2016 SENIOR OFFICERS:</b></div>
<div class="row"><p class="alum"><b class="name">Samantha Caldwell</b> <i>President,</i> Florida State University</p></div>
<div class="row"><p class="alum"><b class="name">Jessica Johnson</b> <i>Vice President,</i> Florida State University</p></div>
<div class="row"><p class="alum"><b class="name">Yarden Ben-David</b> <i>Assistant Vice President,</i> Florida State University</p></div>
<div class="row"><p class="alum"><b class="name">Seren Markovich</b> <i>Secretary,</i> Florida State University</p></div>
<div class="row"><p class="alum"><b class="name">Karina Suarez</b> <i>Historian,</i> Florida International University</p></div>
<div class="row"><p class="alum"><b class="name">Jorge Clero</b> <i>Equipment Manager,</i> Florida Atlantic University</p></div>
<div class="row"><p class="alum title"><b>2016 SENIOR STAFF:</b></p></div>
<div class="row"><p class="alum"><b class="name">Lexi Abrahamoff</b> Florida State University</p></div>
<div class="row"><p class="alum"><b class="name">Jaycee Albury</b> Florida International University</p></div>
<div class="row"><p class="alum"><b class="name">Trace Austin</b> Broward College</p></div>
<div class="row"><p class="alum"><b class="name">Shawn Ebanks</b> Miami Dade College</p></div>
<div class="row"><p class="alum"><b class="name">Samantha Fowler</b> Florida International University</p></div>
<div class="row"><p class="alum"><b class="name">Michael Lynn</b> Nova Southeastern University</p></div>
<div class="row"><p class="alum"><b class="name">Jennifer Nevins</b> Florida State University</p></div>
<div class="row"><p class="alum"><b class="name">Zachary Zucker</b> Full Sail University</p></div>
</div>
<!-- CLASS YEAR END -->




<!-- CLASS YEAR START --><a name="15"></a>
<img class="edge2edge class_of" src="ctv_images/co2015.jpg" alt="Class Of 2015"><div class="stripe">
<div class="row"><p class="alum title"><b>2015 SENIOR OFFICERS:</b></div>
<div class="row"><p class="alum"><b class="name">Hayley Hudson</b> <i>President,</i> Mercer University</p></div>
<div class="row"><p class="alum"><b class="name">Halle Kilman</b> <i>Vice President,</i> University of Central Florida</p></div>
<div class="row"><p class="alum"><b class="name">Shailee Ben-David</b> <i>Assistant Vice President,</i> Florida International University</p></div>
<div class="row"><p class="alum"><b class="name">Brandon Aguiar</b> <i>Secretary,</i> Broward College</p></div>
<div class="row"><p class="alum"><b class="name">Morgan Correa</b> <i>Historian,</i> Tallahassee Community College</p></div>
<div class="row"><p class="alum"><b class="name">Madison Sica</b> <i>Equipment Manager,</i> Tallahassee Community College</p></div>
<div class="row"><p class="alum title"><b>2015 SENIOR STAFF:</b></p></div>
<div class="row"><p class="alum"><b class="name">Thais Ackerman</b> Mercer University</p></div>
<div class="row"><p class="alum"><b class="name">Zachary Churnetski</b> Emerson College</p></div>
<div class="row"><p class="alum"><b class="name">Zachary Levine</b> University of Central Florida</p></div>
<div class="row"><p class="alum"><b class="name">Joseph Poyastro</b></p></div>
<div class="row"><p class="alum"><b class="name">Austen Prager</b> University of South Florida</p></div>
<div class="row"><p class="alum"><b class="name">Sosha Ribeiro-Ayeh</b> Broward College</p></div>
<div class="row"><p class="alum"><b class="name">Kyle Sabrin</b> University of Central Florida</p></div>
<div class="row"><p class="alum"><b class="name">Andrew Shweky</b> Lake Forest College</p></div>
</div>
<!-- CLASS YEAR END -->



<!-- CLASS YEAR START --><a name="14"></a>
<img class="edge2edge class_of" src="ctv_images/co2014.jpg" alt="Class Of 2014"><div class="stripe">
<div class="row"><p class="alum title"><b>2014 SENIOR OFFICERS:</b></div>
<div class="row"><p class="alum"><b class="name">Rachel Broccoli</b> <i>President,</i> Broward College</p></div>
<div class="row"><p class="alum"><b class="name">Maddison Braddy</b> <i>Vice President,</i> Broward College</p></div>
<div class="row"><p class="alum"><b class="name">Brooke Sustrin</b> <i>Assistant Vice President,</i> Santa Fe Community College</p></div>
<div class="row"><p class="alum"><b class="name">Natasha Davalos</b> <i>Secretary,</i> Broward College</p></div>
<div class="row"><p class="alum"><b class="name">Andrew Hopper</b> <i>Business Manager,</i> University of Central Florida</p></div>
<div class="row"><p class="alum"><b class="name">Olivia Pascale-Wong</b> <i>Historian,</i> Florida International University</p></div>
<div class="row"><p class="alum"><b class="name">Marti Wein</b> <i>Equipment Manager,</i> University of Central Florida</p></div>
<div class="row"><p class="alum"><b class="name">Wasim Hayatt</b> <i>Operations Manager,</i> University of Central Florida</p></div>
<div class="row"><p class="alum title"><b>2014 SENIOR STAFF:</b></p></div>
<div class="row"><p class="alum"><b class="name">Taylor Axelrod</b> Broward College</p></div>
<div class="row"><p class="alum"><b class="name">Karine Berman</b> Florida Atlantic University</p></div>
<div class="row"><p class="alum"><b class="name">Leanne Bonello</b> Santa Fe College</p></div>
<div class="row"><p class="alum"><b class="name">Jordan Burgs</b> Florida International University</p></div>
<div class="row"><p class="alum"><b class="name">Jason Fabiano</b> Broward College</p></div>
<div class="row"><p class="alum"><b class="name">Nick Zottoli</b> Tallahassee Community College</p></div>
<div class="row"><p class="alum"><b class="name">Sammi Puglisi</b> Nova Southeastern University</p></div>
<div class="row"><p class="alum"><b class="name">Marco Van Hilst</b> University of Central Florida</p></div>
<div class="row"><p class="alum"><b class="name">Robert Meadows</b> Broward College</p></div>
<div class="row"><p class="alum"><b class="name">Alexis Sherwood-Cotto</b> Florida State University</p></div>
<div class="row"><p class="alum"><b class="name">Alex Guzman</b> Broward College</p></div>
<div class="row"><p class="alum"><b class="name">Adam Neuguard</b> Broward College</p></div>
<div class="row"><p class="alum title"><b>OTHER DEPARTING STAFF:</b></p></div>
<div class="row"><p class="alum"><b class="name">Casey Guarasci</b> College Academy</p></div>
</div>
<!-- CLASS YEAR END -->



<!-- CLASS YEAR START --><a name="13"></a>
<img class="edge2edge class_of" src="ctv_images/co2013.jpg" alt="Class Of 2013"><div class="stripe">
<div class="row"><p class="alum title"><b>2013 SENIOR OFFICERS:</b></div>
<div class="row"><p class="alum"><b class="name">Mitchel Worley</b> <i>President,</i> Barry University</div>
<div class="row"><p class="alum"><b class="name">Anastasia Pavlinskaya</b> <i>Vice President,</i> University of Central Florida</div>
<div class="row"><p class="alum"><b class="name">Noah Avidan</b> <i>Assistant Vice President,</i> University of Florida</div>
<div class="row"><p class="alum"><b class="name">Jordan Kantor</b> <i>Treasurer,</i> Florida Gulf Coast</div>
<div class="row"><p class="alum"><b class="name">Alexis Marx</b> <i>Secretary,</i> Florida State University</div>
<div class="row"><p class="alum"><b class="name">Jake Miller</b> <i>Equip. Manager,</i> Florida State University</div>
<div class="row"><p class="alum"><b class="name">Adi Braha</b> <i>Bus. Manager,</i> University of Florida</div>
<div class="row"><p class="alum title"><b>2013 SENIOR STAFF:</b></div>
<div class="row"><p class="alum"><b class="name">Trent Austin</b> <i>Sports Director,</i> Stetson University</div>
<div class="row"><p class="alum"><b class="name">Rachel Gross</b> University of Central Florida</div>
<div class="row"><p class="alum"><b class="name">Michael Bett</b> University of Central Florida</div>
<div class="row"><p class="alum"><b class="name">Jaime Dunbabin</b> University of Central Florida</div>
<div class="row"><p class="alum"><b class="name">Jazlyn Cartaya</b> New York University</div>
<div class="row"><p class="alum"><b class="name">Taylor Mandel</b> University of Central Florida</div>
<div class="row"><p class="alum"><b class="name">Joshua Lopez</b> Emmanuel College</div>
<div class="row"><p class="alum"><b class="name">Jordan Patrick</b> Mississipi State University</div>
<div class="row"><p class="alum"><b class="name">Eddie Richards</b> Valencia Community College</div>
<div class="row"><p class="alum"><b class="name">Michele Wasserstrom</b> Florida Gulf Coast University</div>
<div class="row"><p class="alum"><b class="name">Matt Pistone</b> Honorary Member</div>
</div>
<!-- CLASS YEAR END -->



<!-- CLASS YEAR START --><a name="12"></a>
<img class="edge2edge class_of" src="ctv_images/co12-dean.jpg" alt="Class Of 2012"><div class="stripe">
<div class="row"><p class="alum title"><b>2012 SENIOR OFFICERS:</b></div>
<div class="row"><p class="alum"><b class="name">Tara Butler</b> <i>President,</i> Emerson College</div>
<div class="row"><p class="alum"><b class="name">Cori Pratt</b> <i>Vice President,</i> Brigham Young University</div>
<div class="row"><p class="alum"><b class="name">Cody Erickson</b> <i>Assistant Vice President,</i> University of Central Florida</div>
<div class="row"><p class="alum"><b class="name">Danielle Noble</b> <i>Treasurer,</i> Florida State University</div>
<div class="row"><p class="alum title"><b>2012 SENIOR STAFF:</b></div>
<div class="row"><p class="alum"><b class="name">Melanie Berra</b> Santa Fe Community College</div>
<div class="row"><p class="alum"><b class="name">TJ Burch</b> United States Air Force Academy</div>
<div class="row"><p class="alum"><b class="name">Haley Castor</b> Broward College</div>
<div class="row"><p class="alum"><b class="name">Yasmin Flasterstein</b></div>
<div class="row"><p class="alum"><b class="name">Michelle Goldman</b> Florida State University</div>
<div class="row"><p class="alum"><b class="name">Dawson Kelhi</b> Broward College</div>
<div class="row"><p class="alum"><b class="name">Steve Lopez</b></div>
<div class="row"><p class="alum"><b class="name">Natalie McPherson</b> New World School of the Arts</div>
<div class="row"><p class="alum"><b class="name">Gabi Tabib</b></div>
</div>
<!-- CLASS YEAR END -->



<!-- CLASS YEAR START --><a name="11"></a>
<img class="edge2edge class_of" src="ctv_images/co11.jpg"><div class="stripe">
<div class="row"><p class="alum title"><b>2011 SENIOR OFFICERS:</b></div>
<div class="row"><p class="alum"><b class="name">Jody Steel</b> <i>President,</i> Emerson College</div>
<div class="row"><p class="alum"><b class="name">Seth Lyon</b> <i>Vice President</i></div>
<div class="row"><p class="alum"><b class="name">Erin Maloney</b> <i>Historian,</i> The New York Conservatory for Dramatic Arts</div>
<div class="row"><p class="alum title"><b>2011 SENIOR STAFF:</b></div>
<div class="row"><p class="alum"><b class="name">Kiersten Alvarado</b></div>
<div class="row"><p class="alum"><b class="name">Bobby Delfin</b> University of Central Florida</div>
<div class="row"><p class="alum"><b class="name">Kristen Garcia</b> University of Central Florida</div>
<div class="row"><p class="alum"><b class="name">Khaled Hassan</b> University of Florida</div>
<div class="row"><p class="alum"><b class="name">Rachel Hoyle</b> University of Central Florida</div>
<div class="row"><p class="alum"><b class="name">Ryan Lynn</b></div>
<div class="row"><p class="alum"><b class="name">Sarah Morris</b> Florida State University</div>
<div class="row"><p class="alum"><b class="name">Colin Neff</b> Florida State University</div>
<div class="row"><p class="alum"><b class="name">Mary Newsome</b></div>
<div class="row"><p class="alum"><b class="name">Ryan Noon</b></div>
<div class="row"><p class="alum"><b class="name">Myles Notkin</b> Florida State University</div>
<div class="row"><p class="alum"><b class="name">Dillon Puswald</b> Emerson College</div>
<div class="row"><p class="alum"><b class="name">Dustin Schreiber</b></div>
<div class="row"><p class="alum"><b class="name">Chris Schultze</b></div>
<div class="row"><p class="alum"><b class="name">Maxine Shepard</b> University of Texas at Austin</div>
<div class="row"><p class="alum"><b class="name">Myles Sica</b> Florida State University</div>
<div class="row"><p class="alum"><b class="name">Hannah Sutker</b> University of Central Florida</div>
<div class="row"><p class="alum"><b class="name">Michael Tromans</b> University of South Florida</div>
</div>
<!-- CLASS YEAR END -->



<!-- CLASS YEAR START --><a name="10"></a>
<img class="edge2edge class_of" src="ctv_images/co10.jpg"><div class="stripe">
<div class="row"><p class="alum title"><b>2010 SENIOR OFFICERS:</b></div>
<div class="row"><p class="alum"><b class="name">Francesca Capua</b> <i>President</i>, Florida State University</b></div>
<div class="row"><p class="alum"><b class="name">Angela Robledo</b> <i>Vice President</i>, Florida State University</div>
<div class="row"><p class="alum"><b class="name">Nicole Payton</b> <i>Assistant Vice President</i>, New York University</div>
<div class="row"><p class="alum"><b class="name">Richard Povian</b> <i>Business Manager</i></div>
<div class="row"><p class="alum"><b class="name">Jessica Alpern</b> <i>Secretary</i>, University of Florida</div>
<div class="row"><p class="alum"><b class="name">Corrina Dolan</b> <i>Treasurer</i>,  Florida State University</div>
<div class="row"><p class="alum title"><b>2010 SENIOR STAFF:</b></div>
<div class="row"><p class="alum"><b class="name">Ben Cohen</b> Florida Atlantic University</div>
<div class="row"><p class="alum"><b class="name">Jeremy Green</b> Florida State University</div>
<div class="row"><p class="alum"><b class="name">Michael Juliano</b></div>
<div class="row"><p class="alum"><b class="name">Lauren Lopilato</b> University of North Carolina at Wilmington, Florida State University</div>
<div class="row"><p class="alum"><b class="name">Max Mittler</b> Florida State University</div>
<div class="row"><p class="alum"><b class="name">JP Palaez</b> Florida State University</div>
<div class="row"><p class="alum"><b class="name">Taylor Slingerland</b> Florida State University</div>
<div class="row"><p class="alum"><b class="name">Brittany Stout</b> University of South Florida</div>
<div class="row"><p class="alum"><b class="name">Michael Tintner</b> University of West Florida</div>
</div>
<!-- CLASS YEAR END -->



<!-- CLASS YEAR START --><a name="09"></a>
<img class="edge2edge class_of" src="ctv_images/co09.jpg"><div class="stripe">
<div class="row"><p class="alum title"><b>2009 SENIOR OFFICERS:</b></div>
<div class="row"><p class="alum"><b class="name">Amanda Katz</b> <i>President</i>, New York University</div>
<div class="row"><p class="alum"><b class="name">Monica Berra</b> <i>Vice President</i>, University of Florida</div>
<div class="row"><p class="alum"><b class="name">Brittany Reeber</b> <i>Assistant Vice President</i>, University of Texas at Austin</div>
<div class="row"><p class="alum"><b class="name">Taylor Tannebaum</b> <i>Business Manager</i>, Florida State University</div>
<div class="row"><p class="alum title"><b>2009 SENIOR STAFF:</b></div>
<div class="row"><p class="alum"><b class="name">Cliff Abbott</b> Broward College</div>
<div class="row"><p class="alum"><b class="name">Michelle Blanck</b> University of Florida</div>
<div class="row"><p class="alum"><b class="name">Chelsea Dinardo</b> University of Florida</div>
<div class="row"><p class="alum"><b class="name">Emily Koplin</b> Florida State University</div>
<div class="row"><p class="alum"><b class="name">Justin Kratish</b> Florida Atlantic University</div>
<div class="row"><p class="alum"><b class="name">Tyler Routley</b> Florida State University</div>
</div>
<!-- CLASS YEAR END -->



<!-- CLASS YEAR START --><a name="08"></a>
<a name="dean"></a><img class="edge2edge class_of" src="ctv_images/co08r.jpg"><div class="stripe">
<div class="row"><p class="alum title"><b>2008 SENIOR OFFICERS:</b></div>
<div class="row"><p class="alum"><b class="name">Dean D'Agati</b> <i>President</i>, New York University
  <a class="alum" style="float:right" href="http://deandagati.com/" target="_blank">deandagati.com</a></p></div>
<div class="row"><p class="alum"><b class="name">Adam Nadel</b> <i>Vice President</i>, Florida State University</div>
<div class="row"><p class="alum"><b class="name">Travis Burch</b> <i>Assistant Vice President</i>, Florida State University</div>
<div class="row"><p class="alum"><b class="name">Melissa Egan</b> <i>Secretary</i>, University of Florida</div>
<div class="row"><p class="alum title"><b>2008 SENIOR STAFF:</b></div>
<div class="row"><p class="alum"><b class="name">Cassie Gonzalez</b> Florida Gulf Coast University</div>
<div class="row"><p class="alum"><b class="name">Jon Griffith</b> University of Central Florida</div>
<div class="row"><p class="alum"><b class="name">Omari Jackson</b> Broward College</div>
<div class="row"><p class="alum"><b class="name">Ben Juster</b> University of Kansas</div>
<div class="row"><p class="alum"><b class="name">Matt Lindeman</b> United States Naval Academy</div>
<div class="row"><p class="alum"><b class="name">Ashley Stout</b> University of Florida</div>
<div class="row"><p class="alum"><b class="name">Sweeney</b> University of Central Florida</div>
<div class="row"><p class="alum"><b class="name">Bryan Vitale</b> Tallahassee Community College</div>
<div class="row"><p class="alum"><b class="name">Andrew Wolf</b> University of Central Florida</div>
</div>
<!-- CLASS YEAR END -->



<!-- CLASS YEAR START -->
<img class="edge2edge class_of" src="ctv_images/co07.jpg"><div class="stripe">
<div class="row"><p class="alum title"><b>2007 SENIOR OFFICERS:</b></div>
<div class="row"><p class="alum"><b class="name">Zak Fine</b> <i>President</i>, University of Florida, Pratt</div>
<div class="row"><p class="alum"><b class="name">Brandon Block</b> <i>Secretary</i>, Auburn University</div>
<div class="row"><p class="alum title"><b>2007 SENIOR STAFF:</b></div>
<div class="row"><p class="alum"><b class="name">Erica Carvalho</b> Florida State University</b></div>
<div class="row"><p class="alum"><b class="name">Chris Dellapace</b> Harding University</b></div>
<div class="row"><p class="alum"><b class="name">Anthony Esteva</b> United States Marine Corps</div>
<div class="row"><p class="alum"><b class="name">Corey Gregg</b> University of Florida</div>
<div class="row"><p class="alum"><b class="name">Alex Hall</b> University of Florida</div>
<div class="row"><p class="alum"><b class="name">Tom Kelleher</b> Florida State University</div>
<div class="row"><p class="alum"><b class="name">Marcel Maynard</b> Broward College</div>
<div class="row"><p class="alum"><b class="name">Kyle Notkin</b> University of Central Florida</div>
<div class="row"><p class="alum"><b class="name">Olivia Smalley</b></div>
<div class="row"><p class="alum"><b class="name">Adam Welsh</b> Columbia College Chicago</div>
<div class="row"><p class="alum"><b class="name">Justin Vandenbroek</b></div>
</div>
<!-- CLASS YEAR END -->



<div style="background-color:black; padding-bottom:20px;">
<p class="style" align="center"><b style="font-size:22px;">Are you a CTV alum?</b><br>To add yourself to this page, change existing info, or add a personal note,<br>e-mail Dean D'Agati at <a href="mailto:deandagati@gmail.com"><font color="white">deandagati@gmail.com</font></a>.<br><br>Note: CTV was created in the early 1990's, but since our website was created in 2006, only our grads from the 06/07 school year onward are available online.</p></div>


<?php require 'footer.php' ?>
