<?php
/*
///##### STOP! #####\\\
DO NOT EDIT THIS FILE DIRECTLY
This file is mamanged by GIT
Contribute at https://github.com/cchsctv/cchsctv.com/
*/
require 'header.php';
require 'topnav.php';
?>
<p> Hello World! </p>
<?php require 'footer.php' ?>
