<?php
/*
///##### STOP! #####\\\
DO NOT EDIT THIS FILE DIRECTLY
This file is mamanged by GIT
Contribute at https://github.com/cchsctv/cchsctv.com/
*/
//require 'header.php';
//require 'topnav.php';
?>
<p> School Events Calendar</p>
<script async src="https://cchsctv.com/cchsroomreservations/Web/scripts/embed-calendar.js?type=month&format=title,date,resource" crossorigin="anonymous"></script>
<?php //require 'footer.php' ?>