<?php
/*
///##### STOP! #####\\\
DO NOT EDIT THIS FILE DIRECTLY
This file is mamanged by GIT
Contribute at https://github.com/cchsctv/cchsctv.com/
*/
$page_title = "Contact";
require 'header.php';
?>
<style type="text/css">
p.style{
  font-size:.75em;
  color:white;
	margin:5px;
	letter-spacing:1px;
  text-align: left;
}
p.head{
	font-size: 22px;
	color:white;
	margin:5px;
	letter-spacing: 2px;
	font-weight: bold;
  text-align: left;
}
p.foot{
	font-size: 14px;
	color:white;
	margin:0px;
	letter-spacing: 1px;
}
#form {
  width:295px;
  height:540px;
  float:left;
}
#left {
  width:calc(100% - 295px);
  height:auto;
  background-color:black;
  float:left;
}
iframe {
  border: none;
}
@media only screen and (max-width: 540px) {
  #form {
    width: 100%;
  }
  #left {
    width: 100%;
  }
}
@media only screen and (max-width: 720px) {
  .topnav a:not(:nth-child(6)) {
    display: none;
  }
  .topnav a:nth-child(6) {
    display: inherit;
  }
}
</style>

<?php
require 'topnav.php';
?>

<!--
<div style="width:342px; height:350px; background-color:black; border:5px solid white; border-right:0px; float:left;"><iframe width="342" height="350" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/place?q=Cooper%20City%20High%20School%2C%20Stirling%20Road%2C%20Cooper%20City%2C%20FL%2C%20United%20States&key=AIzaSyA0jZjxgVDZbl314IrGeVx7ghoYYC41WZE&zoom=7"></iframe></div>
<div style="width:343px; height:350px; background-color:black; border:5px solid white; float:left;"></div>
-->


  <iframe id="form" style="border:0" src="form/contactform.php"></iframe>

<div id="left" style="">
  <iframe width="100%" height="300" style="border:0px solid white; border-bottom:5px solid white;" src="https://www.google.com/maps/embed/v1/place?q=Cooper%20City%20High%20School%2C%20Stirling%20Road%2C%20Cooper%20City%2C%20FL%2C%20United%20States&key=AIzaSyA0jZjxgVDZbl314IrGeVx7ghoYYC41WZE&zoom=7"></iframe>

<p class="head">VIA EMAIL</p>
<p class="style">We encourage you to send us your comments, questions, and/or suggestions by filling out and submiting the forms to the left, or by e-mailing CTV's advisor, Mr. Alfredo Pichardo, at <a href="mailto:apichardo@cchsctv.com">apichardo@cchsctv.com</a>.</p>
<br>
<p class="head">VIA PHONE</p>
<p class="style">Call Cooper City High School at (754) 323-0200 and ask to be directed to CTV. CCHS will not transfer your call while classes are in session (7:30AM to 2:30PM). During this time, you can leave a voicemail or e-mail your question.</p>

</div>

<center><img style="width:calc(100% - 10px); border-top:5px solid white; height:auto" src="ctv_images/lower-banner.jpg" alt="" usemap="imgmap20155214647"><map id="imgmap20155214647" name="imgmap20155214647"><area shape="rect" alt="Cooper City High" title="" coords="88,49,195,71" href="http://www.coopercityhigh.net" target="_blank" /><area shape="rect" alt="Broward County Public Schools" title="" coords="322,50,432,72" href="http://www.browardschools.com" target="_blank" /><area shape="rect" alt="Cooper City, Florida" title="" coords="564,49,660,70" href="http://www.coopercityfl.org" target="_blank" /></map></center>

<?php require 'footer.php' ?>
