<?php
/*
///##### STOP! #####\\\
DO NOT EDIT THIS FILE DIRECTLY
This file is mamanged by GIT
Contribute at https://github.com/cchsctv/cchsctv.com/
*/

// Use in the "Post-Receive URLs" section of your GitHub repo.

if ( $_POST['payload'] ) {
<<<<<<< HEAD
  $output = shell_exec( 'cd /home/ctvserver/public_html && git reset --hard HEAD && git pull' ); 
  error_log($output, 3, "/var/tmp/my-errors.log");
  echo "$output";
} else {
  echo "hi"
}
?>
=======
  //$output = shell_exec( 'cd /home/ctvserver/public_html && git reset --hard HEAD && git pull' ); 
  $output = shell_exec( 'cd /home/ctvserver/public_html && git fetch --all && git reset --hard origin/master' ); 
  error_log("$output", 3, "./git_errors");
  echo "$output";
} else {
  echo "hi";
}
?>
>>>>>>> master
