<?php
/*
///##### STOP! #####\\\
DO NOT EDIT THIS FILE DIRECTLY
This file is mamanged by GIT
Contribute at https://github.com/cchsctv/cchsctv.com/
*/
?>

<!DOCTYPE html>
<!--
 CCCCCTTTTTTTTVV     VV
CC       TTT   VV   VV
CC       TTT    VV VV
 CCCCC   TTT     VVV

Contribute at https://github.com/cchsctv/cchsctv.com/
-->
<html lang="en">
  <head>
    <link rel="shortcut icon" href="ctv_images/favicon.png">
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>
      <?php echo isset($page_title) ? "CTV - $page_title": 'CTV - Cooper City High School'; ?>
    </title>
