<?php
/*
///##### STOP! #####\\\
DO NOT EDIT THIS FILE DIRECTLY
This file is mamanged by GIT
Contribute at https://github.com/cchsctv/cchsctv.com/
*/
$page_title = "Lariat Embed";
require 'header.php';
?>
<base target="_parent">
</head>
<body>
<?php
	$rss = new DOMDocument();
	$rss->load('http://thelariatonline.com/feed/');
	$feed = array();
	foreach ($rss->getElementsByTagName('item') as $node) {
		$item = array (
			'title' => $node->getElementsByTagName('title')->item(0)->nodeValue,
			'desc' => $node->getElementsByTagName('description')->item(0)->nodeValue,
			'link' => $node->getElementsByTagName('link')->item(0)->nodeValue,
			'date' => $node->getElementsByTagName('pubDate')->item(0)->nodeValue,
			);
		array_push($feed, $item);
	}
	$limit = 10;
	for($x=0;$x<$limit;$x++) {
		$title = str_replace(' & ', ' &amp; ', $feed[$x]['title']);
		$link = $feed[$x]['link'];
		$description = $feed[$x]['desc'];
		$date = date('l F d, Y', strtotime($feed[$x]['date']));
		echo '<p><strong><a href="'.$link.'" title="'.$title.'">'.$title.'</a></strong><br />';
		echo '<small><em>'.$date.'</em></small>';
		echo '<br>'.$description.'</p>';
	}
?>
<style type="text/css">
  body {
    background-color: #292F33;
    margin:0
  }
  a {color: white;}
  p {
    font-size: .95em;
    line-height: 1.5;
    font-family: HelveticaNeue-Light, Helvetica, Arial, sans-serif;
    color:white;
    padding:10px;
  }
  p:not(:first-child) {
    border-top: 1px solid rgba(145,165,180,.6);
  }
</style>
