<?php
/*
///##### STOP! #####\\\
DO NOT EDIT THIS FILE DIRECTLY
This file is mamanged by GIT
Contribute at https://github.com/cchsctv/cchsctv.com/
*/
?>

</head>
<body>
<link href="style.css" rel="stylesheet">
<div class="main">
  <a class="" href="index.php" style="display:block; line-height:0"> <img src="ctv_images/background_logo.png" style="" data-rjs="3">  </a>
  <div style="background-color:#383838; border-left-style:solid; border-right-style:solid; border-bottom-style:solid; border-width:10px;vertical-align: top;">
  <script>
    function myFunction() {
      var x = document.getElementById("myTopnav");
      if (x.className === "topnav") {
        x.className += " responsive";
      } else {
        x.className = "topnav";
      }
    }
  </script>
  <div class="topnav" id="myTopnav">
    <a href="index.php">Home</a>
    <a href="video.php">Video</a>
    <a href="cast.php">Cast & Crew</a>
    <a href="alumni.php">Alumni</a>
    <a href="awards.php">Awards</a>
    <a href="contact.php">Contact</a>
    <a href="javascript:void(0);" style="font-size:30px; margin: 5px; margin-right: 15px;" class="icon" onclick="myFunction()">&#9776;</a>
  </div>
