<?php
/*
///##### STOP! #####\\\
DO NOT EDIT THIS FILE DIRECTLY
This file is mamanged by GIT
Contribute at https://github.com/cchsctv/cchsctv.com/
*/
?>

</head>
<body>
<style type="text/css">
<?php include '../style.css'; ?>
</style>
<div class="main">
  <a class="" href="index.php" style="display:block; line-height:0"> <img src="/admin/admin_images/background_logo.png" data-rjs="3">  </a>
  <div class="content_container">
  <script>
    function myFunction() {
      var x = document.getElementById("myTopnav");
      if (x.className === "topnav") {
        x.className += " responsive";
      } else {
        x.className = "topnav";
      }
    }
  </script>
  <div class="topnav" id="myTopnav">
    <a href="/admin/index.php">Admin Home</a>
    <a href="/index.php">Main Site</a>
    <a href="/admin/video.php">Test Video</a>
    <a href="/admin/xml_edit.php">XML Edit</a>
      <a href="/admin/easy_xml.php">XML Add</a>
    <a href="javascript:void(0);" style="font-size:30px; margin: 5px; margin-right: 15px;" class="icon" onclick="myFunction()">&#9776;</a>
    <?php
    if(isset($_SESSION['admin_auth']))
      echo'
    <form data-ajax="false" method="post">
      <input type="hidden" name="logout" value="true" />
      <button style="float:right;margin-top:0.8em" type="submit" data-role="button" data-mini="true">Log out</button>
    </form>
    ';?>
  </div>
