<?php
/*
///##### STOP! #####\\\
DO NOT EDIT THIS FILE DIRECTLY
This file is mamanged by GIT
Contribute at https://github.com/cchsctv/cchsctv.com/
*/
$page_title = "ADMIN";
require 'header.php';
require "auth.php";
require 'admin_topnav.php';
?>

<style type="text/css">

</style>

<p> Herro World! </p>

<?php require '../footer.php' ?>
