<?php
/*
///##### STOP! #####\\\
DO NOT EDIT THIS FILE DIRECTLY
This file is mamanged by GIT
Contribute at https://github.com/cchsctv/cchsctv.com/
*/
$page_title = "ADMIN";
require 'header.php';

define("API_INCLUDED", true);
include_once "auth.php";
?>

<style type="text/css">
</style>

<form data-ajax="false" method="post">
	<input type="hidden" name="logout" value="true" />
	<button type="submit" data-role="button" data-mini="true">Log out</button>
</form>
