<?php
/*
///##### STOP! #####\\\
DO NOT EDIT THIS FILE DIRECTLY
This file is mamanged by GIT
Contribute at https://github.com/cchsctv/cchsctv.com/
*/
$page_title = "ADMIN";
require '../header.php';
require 'auth.php';
?>
<style type="text/css">
<?php include "admin_css.css"; ?>
.adminbar textarea {
    box-sizing: border-box;
    width: 100%;
		height: calc(100vh - 60px);
}
.aux2 {
  display:grid;
  grid-column-start: 1;
  grid-column-end: 4;
  grid-template-columns: auto 1fr;
  grid-row-gap: 0.25em;
  padding: 0.25em 0.25em;
}
.aux2 .full {
  grid-column-start: 1;
  grid-column-end: 4;
  margin: auto;
}
.aux2 textarea {
  height: 2.5em;
  width: auto;
}
@media only screen and (max-width: 720px) {
  .topnav a:not(:nth-child(6)) {
    display: none;
  }
  .topnav a:nth-child(6) {
    display: inherit;
  }
}
</style>

<?php
require 'admin_topnav.php';
if(isset($_POST['stage'])){
	$contents = $_POST['edited_xml'];
	file_put_contents('passwd.xml', $contents, LOCK_EX);
	echo '<p>Users Updated</p>';
}
if(isset($_POST['discard'])){
	echo '<p>Changes Discarded</p>';
}
?>

<form  class="adminbar" data-ajax="false" method="post">
  <button style="float:left" name="discard" type="submit" data-role="button" data-mini="true">Discard Changes</button>
  <p><b>Staging Preview</b></p>
	<button style="float:right" name="stage" type="submit" data-role="button" data-mini="true">Commit Changes</button>
  <textarea style="grid-area: aux;" name="edited_xml">
<?php
$to_edit = (file_exists('passwd.xml')) ? file_get_contents('passwd.xml') : '<?xml version="1.0" encoding="UTF-8"?>
<users>
  <user>
    <username>chua</username>
    <password>$2y$10$ZKcmwMqu.rYQJzOA8vuO5ezyuHnus/RfPkb.OOAho/9gYrwIYMh9C</password>
  </user>
</users>';
echo $to_edit;
?>
	</textarea>
</form>
<form class='aux2' data-ajax="false" method="post">
  <p class='full'><b>Password Hashing</b></p>
  <label>Password To hash: </label>
  <textarea name="to_hash"></textarea>
  <button class='full' name="hash" type="submit" data-role="button" data-mini="true">Hash</button>
  <label>Hashed Password</label>
  <textarea disabled name="output"><?php
  if(isset($_POST['to_hash'])){
echo password_hash($_POST['to_hash'], PASSWORD_DEFAULT);
  }
  ?>
  </textarea>
</form>

<?php require '../footer.php' ?>
