<?php
/*
///##### STOP! #####\\\
DO NOT EDIT THIS FILE DIRECTLY
This file is mamanged by GIT
Contribute at https://github.com/cchsctv/cchsctv.com/
*/
$page_title = "ADMIN";
require '../header.php';
require 'auth.php';
?>
<style type="text/css">
<?php include "admin_css.css"; ?>
textarea {
    box-sizing: border-box;
    height: 2.5em;
}
.aux{
  grid-area: aux;
  background-color:#383838;
  display:grid;
  grid-template-columns: auto 1fr;
  grid-row-gap: 0.25em;
  padding: 0.25em 0.25em;
}
@media only screen and (max-width: 720px) {
  .topnav a:not(:nth-child(4)) {
    display: none;
  }
  .topnav a:nth-child(4) {
    display: inherit;
  }
}
</style>
<p>
<?php
require 'admin_topnav.php';
$contents = "";
if(isset($_POST['stage'])){
  $max = $_POST['max'];
  $out = "";

  function triangleBL($max,&$out){
    $triangle = 0;
    $triangleb = $max;
    for($i = $triangleb;$i > 0;$i--){
      for($b = $triangle+1;$b > 0;$b--){
        $out = $out."*";
      }
      for($t = $triangleb-1;$t > 0;$t--){
        $out = $out." ";
      }
      $triangleb--;
      $triangle++;
      $out = $out.'\n';
    }
  }
  function triangleBR($max,&$out){
    $triangle = 0;
    $triangleb = $max;
    for($i = $triangleb;$i > 0;$i--){
      for($t = $triangleb-1;$t > 0;$t--){
        $out = $out." ";
      }
      for($b = $triangle+1;$b > 0;$b--){
        $out = $out."*";
      }
      $triangleb--;
      $triangle++;
      $out = $out.'\n';
    }
  }
  function triangleTL($max,&$out){
    $triangle = 0;
    $triangleb = $max;
    for($i = $triangleb;$i > 0;$i--){
      for($b = $triangleb;$b > 0;$b--){
        $out = $out."*";
      }
      for($t = $triangle;$t > 0;$t--){
        $out = $out." ";
      }
      $triangle++;
      $triangleb--;
      $out = $out.'\n';
    }
  }
  function triangleTR($max,&$out){
    $triangle = 0;
    $triangleb = $max;
    for($i = $triangleb;$i > 0;$i--){
      for($t = $triangle;$t > 0;$t--){
        $out = $out." ";
      }
      for($b = $triangleb;$b > 0;$b--){
        $out = $out."*";
      }
      $triangle++;
      $triangleb--;
      $out = $out.'\n';
    }
  }
  triangleBL($max,$out);
  $out = $out.'\n';
  triangleBR($max,$out);
  $out = $out.'\n';
  triangleTL($max,$out);
  $out = $out.'\n';
  triangleTR($max,$out);
   echo "<script>console.log( '" . $out . "' );</script>";
}
?>
</p>

<form  class="adminbar" data-ajax="false" method="post">
  <button style="float:left" name="discard" type="submit" data-role="button" data-mini="true">Discard Changes</button>
  <p><b>Staging Preview</b></p>
	<button style="float:right" name="stage" type="submit" data-role="button" data-mini="true">Stage Changes</button>
  <div class="aux">
  <label>Max: </label><textarea name="max"></textarea>
</div>
</form>
<p>See console!</p>
<?php require '../footer.php' ?>
